USE SKATE_SHOP_CODER;

SELECT NUM_CLIENTES() AS NUMERO_CLIENTES;
SELECT NUM_VENTAS() AS CANTIDAD_VENTAS;
SELECT INGRESOS_TOTALES() AS INGRESOS_TOTALES;
SELECT PROMEDIO_VENTAS() AS PROMEDIO_TOTALES;
SELECT MAYOR_VENTA() AS MEJOR_VENTA;
SELECT MENOR_VENTA() AS MENOR_VENTA;

CALL CREAR_TIPO_PAGO("TRUEQUEEEEEE");
CALL OBTENER_TIPO_PAGO();
CALL ACTUALIZAR_TIPO_PAGO (5, "PAGAR CON MONEDAS DE CUERO");
CALL BORRAR_TIPO_PAGO (5);
CALL CREAR_TIPO_CLIENTE("EMPRENDEDOR");
CALL OBTENER_TIPO_CLIENTE();
CALL ACTUALIZAR_TIPO_CLIENTE (5, "VENDEDOR AMBULANTE");
CALL BORRAR_TIPO_CLIENTE (5);