USE SKATE_SHOP_CODER;

CREATE FUNCTION IF NOT EXISTS NUM_CLIENTES() 
    RETURNS INT
    BEGIN
        DECLARE NUMERO_CLIENTES INT;
        SELECT COUNT(*) INTO NUMERO_CLIENTES
        FROM CLIENTE;
        RETURN NUMERO_CLIENTES;
    END;

CREATE FUNCTION IF NOT EXISTS NUM_VENTAS() RETURNS INT
    BEGIN
        DECLARE NUMERO_VENTAS INT;
        SELECT COUNT(*) INTO NUMERO_VENTAS
        FROM FACTURACION;
        RETURN NUMERO_VENTAS;
    END;

CREATE FUNCTION IF NOT EXISTS INGRESOS_TOTALES() RETURNS FLOAT
    BEGIN
        DECLARE SUMATORIA_VENTAS FLOAT;
        SELECT SUM(PRECIO) INTO SUMATORIA_VENTAS
        FROM FACTURACION;
        RETURN SUMATORIA_VENTAS;
    END;

CREATE FUNCTION IF NOT EXISTS PROMEDIO_VENTAS() RETURNS FLOAT
    BEGIN
        DECLARE PROMEDIO_VENTAS FLOAT;
        SELECT AVG(PRECIO) INTO PROMEDIO_VENTAS
        FROM FACTURACION;
        RETURN PROMEDIO_VENTAS;
    END;

CREATE FUNCTION IF NOT EXISTS MAYOR_VENTA( ) RETURNS FLOAT
    BEGIN
        DECLARE MAYOR_VENTA FLOAT;
        SELECT MAX(PRECIO) INTO MAYOR_VENTA
        FROM FACTURACION;
        RETURN MAYOR_VENTA;
    END;

CREATE FUNCTION IF NOT EXISTS MENOR_VENTA( ) RETURNS FLOAT
    BEGIN
        DECLARE MENOR_VENTA FLOAT;
        SELECT MIN(PRECIO) INTO MENOR_VENTA
        FROM FACTURACION;
        RETURN MENOR_VENTA;
    END;