USE SKATE_SHOP_CODER;

CREATE TRIGGER IF NOT EXISTS CREATE_TIPO_PAGO AFTER
INSERT ON TIPO_PAGO FOR EACH ROW
BEGIN
INSERT INTO ACCIONES_TIPO_PAGO (ACCION) VALUES (CONCAT("SE CREO UN REGISTRO EN TIPO DE PAGO CON EL NOMBRE:", NEW.TIPO_PAGO, "y su ID es:", NEW.ID_PAGO));
END;

CREATE TRIGGER IF NOT EXISTS CREATE_TIPO_CLIENTE AFTER 
INSERT ON TIPO_CLIENTE FOR EACH ROW
BEGIN INSERT INTO ACCIONES_TIPO_CLIENTE (ACCION) VALUES (CONCAT("SE CREO UN REGISTRO EN TIPO DE CLIENTE CON EL NOMBRE: ", NEW.TIPO, "y su ID es:", NEW.ID_TIPO));
END;
