CREATE DATABASE IF NOT EXISTS SKATE_SHOP_CODER;

USE SKATE_SHOP_CODER;

CREATE TABLE IF NOT EXISTS MATERIAL (
    ID_MATERIAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MATERIAL VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TECNOLOGIA (
    ID_TECNOLOGIA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TECNOLOGIA VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS TALLA (
    ID_TALLA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TALLA VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS MARCA (
    ID_MARCA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    MARCA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENVIO (
    ID_ENVIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ENVIO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS CIUDAD (
    ID_CIUDAD INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CIUDAD VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PAIS (
    ID_PAIS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    PAIS VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS TIPO_CLIENTE (
    ID_TIPO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA_ARTICULO (
    ID_CAT INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CAT_ARTICULO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS TIPO_PAGO (
    ID_PAGO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TIPO_PAGO VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
    ID_CIUDAD INT NOT NULL,
    ID_PAIS INT NOT NULL,
    ID_ENVIO INT NOT NULL,
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO(ID_ENVIO)
);

CREATE TABLE IF NOT EXISTS ARTICULO (
    ID_ARTICULO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRECIO FLOAT NOT NULL,
    COSTO FLOAT NOT NULL,
    ID_CAT INT NOT NULL,
    ID_TALLA INT NOT NULL,
    ID_TECNOLOGIA INT NOT NULL,
    ID_MATERIAL INT NOT NULL,
    FOREIGN KEY (ID_CAT) REFERENCES CATEGORIA_ARTICULO(ID_CAT),
    FOREIGN KEY (ID_TALLA) REFERENCES TALLA(ID_TALLA),
    FOREIGN KEY (ID_TECNOLOGIA) REFERENCES TECNOLOGIA(ID_TECNOLOGIA),
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL(ID_MATERIAL)
);

CREATE TABLE IF NOT EXISTS FACTURA (
    ID_FACTURA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FACTURA VARCHAR(255),
    ID_PAGO INT NOT NULL,
    FOREIGN KEY (ID_PAGO) REFERENCES TIPO_PAGO(ID_PAGO)
);

CREATE TABLE IF NOT EXISTS FACTURACION (
    ID_VENTA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NUM_FACTURA VARCHAR(255) NOT NULL,
    ID_FACTURA INT NOT NULL,
    ID_ARTICULO INT NOT NULL,
    ID_MARCA INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_CIUDAD INT NOT NULL,
    ID_PAIS INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO FLOAT NOT NULL,
    COSTO FLOAT NOT NULL,
    ID_PAGO INT NOT NULL,
    ID_TIPO INT NOT NULL,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_CLIENTE(ID_TIPO),
    FOREIGN KEY (ID_PAGO) REFERENCES TIPO_PAGO(ID_PAGO),
    FOREIGN KEY (ID_PAIS) REFERENCES PAIS(ID_PAIS),
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA),
    FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO),
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA)
);

CREATE TABLE IF NOT EXISTS ACCIONES_TIPO_PAGO(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ACCION VARCHAR(255),
    FECHA DATETIME NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ACCIONES_TIPO_CLIENTE(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ACCION VARCHAR(255),
    FECHA DATETIME NULL DEFAULT CURRENT_TIMESTAMP
);